- name: Users Linux
  hosts: all
  become: true
  # vars_files:
  #   - group_vars/all.yml
  roles:
    # - role: prepare-server
    #   tags: prepare

    # - role: users-and-groups
    #   tags: users

    # - role: access-control
    #   tags: access

    # - role: config-nginx
    #   tags: nginx

    # - role: user-roles-config
    #   tags: sudoersd

    - role: umask
      tags: umask
